apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: ep-lucky-thunder-ag4fkq9c-pooler.c-2.eu-central-1.aws.neon.tech
  DB_PORT: "5432"
  DB_NAME: neondb
  DB_USER: neondb_owner
  DB_PASSWORD: npg_bsmaJSdM84XO