kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: my-ds
spec:
  selector:
    matchLabels:
      app: my-ds
  template:
    metadata:
      labels:
        app: my-ds
    spec:
      containers:
      - name: my-ds
        image: nginx
        ports:
        - containerPort: 3000