FROM node:18-alpine AS build
WORKDIR /frontend
COPY ./frontend/package.json ./
RUN npm install
COPY ./frontend/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
