FROM ubuntu:latest AS builder
RUN apt update && apt install -y gcc
COPY hello.c /opt/hello.c
RUN gcc /opt/hello.c -o /opt/hello

FROM ubuntu:latest
COPY --from=builder /opt/hello /opt/hello
CMD ["/opt/hello"]